[tool.poetry]
name = "selenium-click"
version = "0.1.0"
description = ""
authors = ["mac <bisane.swaraj@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
